language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
install:
 - pip install -r requirements.txt
script:
 - env PYTHONPATH=python agent/fixtool-agent
 - cd python/tests
 - env PYTHONPATH=.. python -m unittest --verbose all
 - cd ..
 - env PYTHONPATH=. coverage run tests/all.py
 - cd ..
 - env PYTHONPATH=python agent/fixtool-agent shutdown
after_success:
 - coveralls
