language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
- pip install -r requirements.txt
script:
 - cd python/tests
 - env PYTHONPATH=.. python -m unittest --verbose all
 - cd ..
 - env PYTHONPATH=. coverage run tests/all.py
after_success:
 - coveralls
