language: python
python:
 - "3.5"
 - "3.6"
install:
 - pip install -r requirements.txt
script:
 - env PYTHONPATH=python python agent/fixtool-agent.py &
 - cd python/tests
 - env PYTHONPATH=.. python -m unittest --verbose all
 - cd ..
 - env PYTHONPATH=. coverage run tests/all.py
 - cd ..
 - env PYTHONPATH=python python agent/fixtool-agent.py shutdown
after_success:
 - coveralls
